//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateurLicences.Localisation {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessagesSystem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesSystem() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GenerateurLicences.Localisation.MessagesSystem", typeof(MessagesSystem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bienvenue.
        /// </summary>
        public static string Bienvenue {
            get {
                return ResourceManager.GetString("Bienvenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Client  Express ajouté dans la base de donnée.
        /// </summary>
        public static string ClientAddSuccecful {
            get {
                return ResourceManager.GetString("ClientAddSuccecful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur de connection à la base de donnée.
        /// </summary>
        public static string DataBaseConnectionFailed {
            get {
                return ResourceManager.GetString("DataBaseConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre connection a commencée  le :.
        /// </summary>
        public static string DebutConnection {
            get {
                return ResourceManager.GetString("DebutConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur : Aucun numero de licence n&apos;a été generer pour ce client !                                                                                        ou numero de licence trop long pour etre ennregistrer dans la base de donner.
        /// </summary>
        public static string EmptyNumLicence {
            get {
                return ResourceManager.GetString("EmptyNumLicence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un Minimum d&apos;informations requise :les champs Code Client et Zip sont obligatoire.
        /// </summary>
        public static string ErreurAjoutClientExpress {
            get {
                return ResourceManager.GetString("ErreurAjoutClientExpress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucune  licence n&apos;a été genrer pour ce client merci de verifier le codeclient.
        /// </summary>
        public static string ErreurConsulterDetails {
            get {
                return ResourceManager.GetString("ErreurConsulterDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une Erreur Inconnue C&apos;est produite.
        /// </summary>
        public static string ErreurInconnue {
            get {
                return ResourceManager.GetString("ErreurInconnue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous avez probablement fait une erreur de saisie lors de la modification  date.
        /// </summary>
        public static string ErreurSaisieDate {
            get {
                return ResourceManager.GetString("ErreurSaisieDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun champ n&apos;est renseigné Veuillez remplir le formulaire SVP.
        /// </summary>
        public static string FormulaireEmpty {
            get {
                return ResourceManager.GetString("FormulaireEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre ot de passe ou votre Nom Administrateur est invalide Merci de Verifié.
        /// </summary>
        public static string IdentifiantInvalide {
            get {
                return ResourceManager.GetString("IdentifiantInvalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Jour(s).
        /// </summary>
        public static string Jours {
            get {
                return ResourceManager.GetString("Jours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Licence pour Mr/Mme :.
        /// </summary>
        public static string LicenceUserName {
            get {
                return ResourceManager.GetString("LicenceUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Licence affecter et enregistrer dans la base de donné pour Mr/Mme :.
        /// </summary>
        public static string LoadDataSucced {
            get {
                return ResourceManager.GetString("LoadDataSucced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save As PDF Files|*.pdf.
        /// </summary>
        public static string MessageSaveAS {
            get {
                return ResourceManager.GetString("MessageSaveAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ImprimerLicence.
        /// </summary>
        public static string MessageTitleImprimer {
            get {
                return ResourceManager.GetString("MessageTitleImprimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modification sauvgarder avec succée !.
        /// </summary>
        public static string ModifSaved {
            get {
                return ResourceManager.GetString("ModifSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You forgot to write the administrator&apos;s name.
        /// </summary>
        public static string NomEmpty {
            get {
                return ResourceManager.GetString("NomEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le Champs mot de passe est vide veuillez le renseigné svp.
        /// </summary>
        public static string PasswordEmpty {
            get {
                return ResourceManager.GetString("PasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Licence  client  active et valable encore :.
        /// </summary>
        public static string RepnseVert {
            get {
                return ResourceManager.GetString("RepnseVert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Licence client  active mais elle  va bientot s&apos;achever ,valable encore :.
        /// </summary>
        public static string ReponseOrange {
            get {
                return ResourceManager.GetString("ReponseOrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Licence client expirer nombre de jour de dépassement  :.
        /// </summary>
        public static string ReponseRouge {
            get {
                return ResourceManager.GetString("ReponseRouge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous avez selectionner aucune option de licence   :.
        /// </summary>
        public static string StringEmpty {
            get {
                return ResourceManager.GetString("StringEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;&quot;.
        /// </summary>
        public static string StringVide {
            get {
                return ResourceManager.GetString("StringVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Navigation  Au nom de  :.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
    }
}
