//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateurLicences.Localisation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessagesSystem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesSystem() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GenerateurLicences.Localisation.MessagesSystem", typeof(MessagesSystem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenue.
        /// </summary>
        public static string Bienvenue {
            get {
                return ResourceManager.GetString("Bienvenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client  Express ajouté dans la base de donnée.
        /// </summary>
        public static string ClientAddSuccecful {
            get {
                return ResourceManager.GetString("ClientAddSuccecful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur de connection à la base de donnée.
        /// </summary>
        public static string DataBaseConnectionFailed {
            get {
                return ResourceManager.GetString("DataBaseConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre connection a commencée  le :.
        /// </summary>
        public static string DebutConnection {
            get {
                return ResourceManager.GetString("DebutConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur : Aucun numero de licence n&apos;a été generer pour ce client !                                                                                        ou numero de licence trop long pour etre ennregistrer dans la base de donner.
        /// </summary>
        public static string EmptyNumLicence {
            get {
                return ResourceManager.GetString("EmptyNumLicence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un Minimum d&apos;informations requise :les champs Code Client et Zip sont obligatoire.
        /// </summary>
        public static string ErreurAjoutClientExpress {
            get {
                return ResourceManager.GetString("ErreurAjoutClientExpress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune  licence n&apos;a été genrer pour ce client merci de verifier le codeclient.
        /// </summary>
        public static string ErreurConsulterDetails {
            get {
                return ResourceManager.GetString("ErreurConsulterDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une Erreur Inconnue C&apos;est produite.
        /// </summary>
        public static string ErreurInconnue {
            get {
                return ResourceManager.GetString("ErreurInconnue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous avez probablement fait une erreur de saisie lors de la modification  date.
        /// </summary>
        public static string ErreurSaisieDate {
            get {
                return ResourceManager.GetString("ErreurSaisieDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun champ n&apos;est renseigné Veuillez remplir le formulaire SVP.
        /// </summary>
        public static string FormulaireEmpty {
            get {
                return ResourceManager.GetString("FormulaireEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre ot de passe ou votre Nom Administrateur est invalide Merci de Verifié.
        /// </summary>
        public static string IdentifiantInvalide {
            get {
                return ResourceManager.GetString("IdentifiantInvalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jour(s).
        /// </summary>
        public static string Jours {
            get {
                return ResourceManager.GetString("Jours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licence pour Mr/Mme :.
        /// </summary>
        public static string LicenceUserName {
            get {
                return ResourceManager.GetString("LicenceUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licence affecter et enregistrer dans la base de donné pour Mr/Mme :.
        /// </summary>
        public static string LoadDataSucced {
            get {
                return ResourceManager.GetString("LoadDataSucced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As PDF Files|*.pdf.
        /// </summary>
        public static string MessageSaveAS {
            get {
                return ResourceManager.GetString("MessageSaveAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImprimerLicence.
        /// </summary>
        public static string MessageTitleImprimer {
            get {
                return ResourceManager.GetString("MessageTitleImprimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification sauvgarder avec succée !.
        /// </summary>
        public static string ModifSaved {
            get {
                return ResourceManager.GetString("ModifSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le Champs Nom Administrateur est vide veuillez le renseigné svp.
        /// </summary>
        public static string NomEmpty {
            get {
                return ResourceManager.GetString("NomEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le Champs mot de passe est vide veuillez le renseigné svp.
        /// </summary>
        public static string PasswordEmpty {
            get {
                return ResourceManager.GetString("PasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licence  client  active et valable encore :.
        /// </summary>
        public static string RepnseVert {
            get {
                return ResourceManager.GetString("RepnseVert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licence client  active mais elle  va bientot s&apos;achever ,valable encore :.
        /// </summary>
        public static string ReponseOrange {
            get {
                return ResourceManager.GetString("ReponseOrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licence client expirer nombre de jour de dépassement  :.
        /// </summary>
        public static string ReponseRouge {
            get {
                return ResourceManager.GetString("ReponseRouge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous avez selectionner aucune option de licence   :.
        /// </summary>
        public static string StringEmpty {
            get {
                return ResourceManager.GetString("StringEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;&quot;.
        /// </summary>
        public static string StringVide {
            get {
                return ResourceManager.GetString("StringVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation  Au nom de  :.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
    }
}
